config/routes.rb
Rails.application.routes.draw do
	root :to => "homes#index"
  devise_for :users, controllers: {registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  resources :users, :only =>[:index, :show, :edit, :update] 
  resources :books
  resources :homes, :only =>[:new]
  get "/home/about" => "homes#about"
  post 'follow/:id' => 'relationships#follow', as: 'follow' 
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' 
  get "relationship/:user_id/follows" => "relationships#follows", as:'user_follows'
  get "relationship/:user_id/followers" => "relationships#followers", as:'user_followers'
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def follow
    current_user.follow(params[:id])
    redirect_back(fallback_location: root_path)
  end

  def unfollow
    current_user.unfollow(params[:id])
    redirect_back(fallback_location: root_path)
  end

  def index
  	@users =User.all
  end

  def follows
  	@user = User.find(params[:user_id])
  	@users = @user.following_user
  	render :index
  end

  def followers
  	@user = User.find(params[:user_id])
  	@users = @user.follower_user
  	render :index
 end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/index.html.erb
 <div class="col-md-2">
 </div>
   <div class="col-md-10">
            <div class=de>
              <h2>Users</h2> 
            </div>
              <table class="table">
              <thead>
                <tr>
               <th></th>   
              <th>title</th>
              <th>Opinion</th>
                </tr>
              </thead>
             <% @users.each do |user| %>
	             <tr>
	    	       <td><%= attachment_image_tag user, :profile_image, format: "jpeg", fallback:"no image.jpg", size: "40x40" %></td>
	    	       <td><%= user.name %></td>
               <td>フォロー数 : <%= user.followed.count %></td>
               <td>フォロワー数 : <%= user.follower.count %></td>
               <td>
               <% if current_user.following?(user) %>
                 <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
              <% else %>
                 <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
                <% end %>
              </td>
            <td><%= link_to "Show", user_path(user.id) %></td>
                 </tr>
                 <% end %>
                </tbody>
               </table>
              </div>
           </div>
       </div>
        <div class="top2">
       <p>CopyRight Infratop.inc</p>
     </div>