config/routes.rb
Rails.application.routes.draw do
	root :to => "homes#index"
  devise_for :users, controllers: {registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  resources :users, :only =>[:index, :show, :edit, :update] 
  resources :books
  resources :homes, :only =>[:new]
  get "/home/about" => "homes#about"
  post 'follow/:id' => 'relationships#follow', as: 'follow' 
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' 
  get "relationship/:user_id/follows" => "relationships#follows", as:'user_follows'
  get "relationship/:user_id/followers" => "relationships#followers", as:'user_followers'
end

app/models/user.rb
class User < ApplicationRecord
	validates :name, presence: true
	validates :name, length: {minimum: 2}
	validates :name, length: {maximum: 20}
	validates :introduction, length: {maximum: 50}
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_many :books, dependent: :destroy
   attachment :profile_image

   has_many :relationship
   has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy 
   has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
   has_many :following_user, through: :follower, source: :followed 
   has_many :follower_user, through: :followed, source: :follower 

   
  def follow(user_id)
    follower.create(followed_id: user_id)
  end


  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end


  def following?(user)
    following_user.include?(user)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
 before_action :login_check, only: [:edit]
def index
	  @book=Book.new
    @users =User.all
    @user = current_user
end

def show
	@user = User.find(params[:id])
	@book=Book.new
	@books = @user.books
end

def edit
	@user = User.find(params[:id])

if  @user = current_user

else
	  render "show"	
end
end

def update
	@user =User.find(params[:id])

if  @user.update(user_params)
	flash[:complete] = "You have updated user successfully." 
	redirect_to user_path(@user.id)

else 

     render "edit"	
end
end

private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image )
  end

 def login_check
       @user = User.find(params[:id])
    if @user.id != current_user.id
       redirect_to user_path(current_user)

       
      end
    end
 end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="c">

<%= form_for(@user, url: user_path) do |f| %>
<%= render 'layouts/usererror_messages', model: f.object %>

     <h2>User info</h2> 

    <h4>Name</h4>
    <%= f.text_field :name %>

    <h4>Image</h4>
    <%= f.attachment_field :profile_image %>
 
    <h4>introduction</h4>
    <%= f.text_area :introduction %>
 
    <br><%= f.submit 'Update User', class: "btn btn-primary" %></br>
      <div class="top3">
        <p>CopyRight Infratop.inc</p>
      </div>
<% end %>
</div>

app/views/users/index.html.erb
<div class="container"> 
      <div class="row"> 
      	  <div class="col-xs-3">
      	  	<div class="tl">
              <h2>User info</h2>
              <div class="fy">
               <%= attachment_image_tag @user, :profile_image, format: "jpeg", fallback:"no image.jpg", size: "80x80" %>
             </div>
              <table class="table">
                <tr>
                  <th>name : <%= @user.name %></th>
                </tr>
              </table>
              <table class="table">
                <tr>
      		        <th>introduction : <%= @user.introduction %></th>
                </tr>
                
                <tr>
                  <th>follows : <%= link_to @user.follower.count, user_follows_path(@user.id) %></th>
                </tr>
                <tr>
                  <th>followers : <%= link_to  @user.followed.count, user_followers_path(@user.id) %></th>
                </tr>
                 <tr>
               <th><% if current_user.following?(@user) %>
                 <%= link_to 'フォロー外す', unfollow_path(@user.id), class: 'btn btn-primary ', method: :POST %>
              <% else %>
                 <%= link_to 'フォローする', follow_path(@user.id), class: 'btn btn-success ', method: :POST %>
              </th>
              <% end %>
            </tr>
              </table>
                 <button type="button" class="btnbtn-default btn-sm">
                 <span class="glyphicon glyphicon-wrench"></span>
                 <%= link_to "Wrench", edit_user_path(@user.id) %></button>
      		 </div>
            <div class="top">

              <%= form_for(@book) do |f| %>
               <div class="field row">
              <h2>New book</h2>

 
              <h4>title</h4>
              <%= f.text_field :title %>
              </div>
              
              <div class="field row">
              <h4>Opinion</h4>
              <%= f.text_area :body %>
            </div>
 
             <br><%= f.submit 'Create Book', class:"btn btn-primary" %></br>
            <% end %>
           </div>
          </div>
      	    <div class="col-xs-9">
               <table class="table">
                <div class=de>
                 <h2>Users</h2>
               </div>
	            <thead>
	              <tr>
		            <th>image</th>
		            <th>name</th>
	              </tr>
	            </thead>
	
                <tbody>
		       <% @users.each do |user| %>
	             <tr>
	    	       <td><%= attachment_image_tag user, :profile_image, format: "jpeg", fallback:"no image.jpg", size: "40x40" %></td>
	    	       <td><%= user.name %></td>
               <td>フォロー数 : <%= user.follower.count %></td>
               <td>フォロワー数 : <%= user.followed.count %></td>
               <td>
               <% if current_user.following?(user) %>
                 <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
              <% else %>
                 <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
                <% end %>
              </td>
            <td><%= link_to "Show", user_path(user.id) %></td>
                 </tr>
                 <% end %>
                </tbody>
               </table>
              </div>
           </div>
       </div>
        <div class="top2">
       <p>CopyRight Infratop.inc</p>
     </div>

app/views/users/show.html.erb
<div class="sks">
<%= flash[:complete] %>  

  <p id="notice"><%= notice %></p>
</div>
<div class="container"> 
      <div class="row"> 
      	  <div class="col-xs-3">
      	  	<div class="tl">
              <h2>User info</h2>
              <div class="fy">
               <%= attachment_image_tag @user, :profile_image, format: "jpeg", fallback:"no image.jpg", size: "80x80" %>
             </div>
             <table class="table">
              <tr>
               <th>name : <%= @user.name %></th>
              </tr>
            </table>
            <table class="table">
              <tr>
      		    <th>introduction : <%= @user.introduction %></th>
            </tr>
            <tr>
               <% if user_signed_in? && @user !=current_user %>
              <th>follows : <%= link_to @user.follower.count,  user_follows_path(@user.id) %></th>
            </tr>
            <tr>
              <th>followers : <%= link_to @user.followed.count,  user_followers_path(@user.id) %></th>
            </tr>
             <tr>
               <th><% if current_user.following?(@user) %>
                 <%= link_to 'フォロー外す', unfollow_path(@user.id), class: 'btn btn-primary ', method: :POST %>
              <% else %>
                 <%= link_to 'フォローする', follow_path(@user.id), class: 'btn btn-success ', method: :POST %>
              </th>
              <% end %>
              <% end %>
            </tr>
          </table>

                <% if user_signed_in?  %>
                 <button type="button" class="btnbtn-default btn-sm">
                 <span class="glyphicon glyphicon-wrench"></span>
                 <%= link_to "Wrench",edit_user_path %></button>
                 <% end %>
      		 </div>
            <div class="top">

              <%= form_for(@book) do |f| %>
              <div class="field row">
              <h2>New book</h2>
 
              <h4>title</h4>
              <%= f.text_field :title %>
            </div>
               <div class="field row">
              <h4>Opinion</h4>
              <%= f.text_area :body %>
            </div>
 
             <br><%= f.submit 'Create Book', class:"btn btn-primary" %></br>
            <% end %>
           </div>
          </div>
      	    <div class="col-xs-9">
              <div class=de>
              <h2>Books</h2> 
            </div>
               <table class="table">
	            <thead>
	              <tr>
                <th></th>
		            <th>Title</th>
		            <th>Opinion</th>
	              </tr>
	            </thead>
	
                <tbody>
		       <% @books.each do |book| %>
	             <tr>
             <td><%= link_to attachment_image_tag @user, :profile_image, format: "jpeg", fallback:"no image.jpg", size: "40x40" %></td>
	    	       <td><%= link_to book.title, book_path(book.id) %></td>
                   <td><%= book.body %></td>
                 </tr>
                 <% end %>
                </tbody>
               </table>
              </div>
           </div>
            <div class="top2">
       <p>CopyRight Infratop.inc</p>
     </div>