config/routes.rb
Rails.application.routes.draw do
	root :to => "homes#index"
  devise_for :users, controllers: {registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  resources :users, :only =>[:index, :show, :edit, :update] 
  resources :books
  resources :homes, :only =>[:new]
  get "/home/about" => "homes#about"
  post 'follow/:id' => 'relationships#follow', as: 'follow' 
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' 
  get "relationship/:user_id/follows" => "relationships#follows", as:'user_follows'
  get "relationship/:user_id/followers" => "relationships#followers", as:'user_followers'
end

app/models/book.rb
class Book < ApplicationRecord
	 belongs_to :user
	 validates :title, :body, presence: true
	 validates :body, length: {maximum: 200}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!
before_action :login_check, only: [:edit]
	
def edit
  if  @book = current_user.books.find_by(id: params[:id])

  else
  	 redirect_to books_path
 end
end

def update
	@book =Book.find(params[:id])
	@book.user_id = current_user.id

 if @book.update(book_params)
    flash[:complete] = "You have creatad book successfully." 
	redirect_to book_path(@book.id)
else
    render "edit"	
end
end

def show	
	@book =Book.find(params[:id])
	@books = Book.page(params[:page])
	@users = User.all
	@user = @book.user
end

def destroy
	 book = Book.find(params[:id])
     book.destroy
     redirect_to books_path
end

def index
	@user = current_user
	@users =User.all
	@book = Book.new
	@books = Book.all
end

def create
	@book =Book.new(book_params)
    @book.user_id = current_user.id

if  @book.save
    flash[:complete] = "You have creatad book successfully." 
	redirect_to book_path(@book.id)	
else
	@books = Book.all
	@user = current_user
	render"index"
end
end

private
def book_params
    params.require(:book).permit(:title, :body)
end
def login_check
 	unless user_signed_in?
 	redirect_to user_path
  end
end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div class="container"> 
      <div class="row"> 
<div class="text-center">
	<div class="col-md-12">
        <div class="ded">
 
<%= form_for(@book) do |f| %>
<%= render 'layouts/bookerror_massages', model: f.object %>
<h2>Editing Book</h2>

    <h4>title</h4>
    <%= f.text_field :title %>
 
    <h4>Opinion</h4>
    <%= f.text_area :body %>
 
    <br><%= f.submit 'Update Book', class: "btn btn-primary" %></br>
    <br><%= link_to "Show", book_path %>
        <%= link_to "Back", books_path %></br>
        <div class="top1">
        <p>CopyRight Infratop.inc</p>
    </div>
  </div>
 
<% end %>
</div>
</div>
</div>
</div>

app/views/books/index.html.erb
<div class="container"> 
      <div class="row"> 
      	<div class="col-xs-3">
            <div class="tl">
            	 <h2>User info</h2>
               <div class="fy">
                <%= attachment_image_tag @user, :profile_image, format: "jpeg", fallback:"no image.jpg", size: "80x80" %>
             </div>
              <table class="table">
                <tr>
                 <th>name : <%= @user.name %></th>
                </tr>
              </table>
              <table class="table">
                <tr>
                 <th>introduction : <%= @user.introduction %></th>
                </tr>
                <tr>
                  <th>follows : <%= link_to @user.follower.count, user_follows_path(@user.id) %></th>
                </tr>
                <tr>
                  <th>followers : <%= link_to @user.followed.count, user_followers_path(@user.id) %></th>
                </tr>
                 <tr>
               <th><% if current_user.following?(@user) %>
                 <%= link_to 'フォロー外す', unfollow_path(@user.id), class: 'btn btn-primary ', method: :POST %>
              <% else %>
                 <%= link_to 'フォローする', follow_path(@user.id), class: 'btn btn-success ', method: :POST %>
              </th>
              <% end %>
            </tr>
              </table>
                   <button type="button" class="btnbtn-default btn-sm">
                   <span class="glyphicon glyphicon-wrench"></span>
                   <%= link_to "Wrench", edit_user_path(@user.id) %></button>
            </div>
           <div class="top">

            <%= form_for(@book) do |f| %>
            <%= render 'layouts/bookerror_massages', model: f.object %>
            <div class="field row">
            <h2>New book</h2>
 
            <h4>title</h4>
            <%= f.text_field :title %>
          </div>

             <div class="field row"> 
            <h4>Opinion</h4>
             <%= f.text_area :body %>
           </div>
 
             <br><%= f.submit 'Create Book',class:"btn btn-primary"%></br>
            <% end %>
           </div>
          </div>
          <div class="col-xs-9">
            <div class=de>
              <h2>Books</h2> 
            </div>
              <table class="table">
	            <thead>
	              <tr>
               <th></th>   
		          <th>title</th>
		          <th>Opinion</th>
	              </tr>
	            </thead>
	
	         <tbody>
		        <% @books.each do |book| %>
	             <tr> 
                <td><%= link_to user_path(book.user.id) do %>
                  <%=  attachment_image_tag book.user,  :profile_image, format: "jpeg", fallback:"no image.jpg", size: "40x40" %></td>
                <% end %>
	    	     <td><%= link_to book.title, book_path(book.id)  %></td>
	    	     <td><%= book.body %></td>
                 </tr>
              <% end %>
             </tbody>
             </table>
           </div>
         </div>
       </div>
       <div class="top2">
       <p>CopyRight Infratop.inc</p>
     </div>

app/views/books/show.html.erb
<div class="sks">
<%= flash[:complete] %> 

  <p id="notice"><%= notice %></p>
</div>
<div class="container"> 
      <div class="row"> 
          <div class="col-xs-3">
            <div class="tl">
              <h2>User info</h2>
               <%= attachment_image_tag @user, :profile_image, format: "jpeg", fallback:"no image.jpg", size: "80x80" %>
               <table class="table">
               <tr>
              <th>name : <%= @user.name %></th>
            </tr>
             </table>
             <table class="table">
              <th>introduction : <%= @user.introduction %></th>
            </tr>

            <tr>
              <th>follows : <%= link_to @user.follower.count, user_follows_path(@user.id) %></th>
            </tr>
            <tr>
              <th>followers : <%= link_to @user.followed.count, user_followers_path(@user.id) %></th>
            </tr>
             <tr>
               <th><% if current_user.following?(@user) %>
                 <%= link_to 'フォロー外す', unfollow_path(@user.id), class: 'btn btn-primary ', method: :POST %>
              <% else %>
                 <%= link_to 'フォローする', follow_path(@user.id), class: 'btn btn-success ', method: :POST %>
              </th>
              <% end %>
            </tr>
          </table>
               <% if user_signed_in?  %>
                 <button type="button" class="btnbtn-default btn-sm">
                 <span class="glyphicon glyphicon-wrench"></span>
                 <%= link_to "Wrench", edit_user_path(@user.id) %></button>
                 <% end %>
           </div>
            <div class="top">

           <%= form_for(@book) do |f| %>
            <div class="field row">
               <h2>New book</h2>
              <h4>title</h4>
              <%= f.text_field :title %>
            </div>
              
            <div class="field row">
              <h4>Opinion</h4>
              <%= f.text_area :body %>
            </div>
 
             <br><%= f.submit 'Create Book', class:"btn btn-primary" %></br>
            <% end %>
           </div>
          </div>
            <div class="col-xs-9">
               <table class="table">
              <thead>
                <div class=de>
                <h2>Book detail</h2> 
              </div>
              </thead>
  
                <tbody>
               <tr>
                <td><%= link_to user_path(@user.id) do %>
                    <%=  attachment_image_tag @user,  :profile_image, format: "jpeg", fallback:"no image.jpg", size: "40x40" %>
                    <br><%= @user.name %></br>
                </td>
                <% end %>
                <td><%= link_to @book.title  %></td>
                <td><%= @book.body %></td>
                <td>
                    <% if user_signed_in? && current_user.id == @book.user_id %>
                    <%= link_to "Edit", edit_book_path(@book.id) %>
                    <%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "Are you sure?" %>
                    <% end %>
                </td>
               </tr>
            </tbody>
           </table>
          </div>
        </div>
      </div>
       <div class="top2">
       <p>CopyRight Infratop.inc</p>
     </div>