config/routes.rb
Rails.application.routes.draw do
	root :to => "homes#index"
  devise_for :users, controllers: {registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  resources :users, :only =>[:index, :show, :edit, :update] 
  resources :books
  resources :homes, :only =>[:new]
  get "/home/about" => "homes#about"
  post 'follow/:id' => 'relationships#follow', as: 'follow' 
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' 
  get "relationship/:user_id/follows" => "relationships#follows", as:'user_follows'
  get "relationship/:user_id/followers" => "relationships#followers", as:'user_followers'
end

app/views/layouts/_bookerror_massages.html.erb
<% if @book.errors.any? %>
<h3><%= @book.errors.count %>errors prohibited this  from being saved:</h3>
<ul>
  <% @book.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/_usererror_messages.html.erb
<% if @user.errors.any? %>
<h3><%= @user.errors.count %>errors prohibited this  from being saved:</h3>
<ul>
  <% @user.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <div id="slidemenu">
        <nav class="navbar navbar-fixed-top navbar-inverse">
      <h4><span class="navbar-text">Bookers</span></h4>
  <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
    <% if user_signed_in? %>
       <li class="">
        <%= link_to 'Home', user_path(current_user.id) %>
      </li>
      <li class="">
        <%= link_to 'Users', users_path %>
      </li>
       <li class="">
        <%= link_to 'Books', books_path %>
      </li>
      <li class="">
        <%= link_to "logout", destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
       <li><a class="glyphicon glyphicon-home home" href="/"> Home</a></li>
      </li>
       <li><a class="glyphicon glyphicon-link about" href="/home/about"> About</a></li>
      </li>
       <li><a class="glyphicon glyphicon-edit sign_up" href="/users/sign_up"> sign up</a></li>
      </li>
      <li><a class="glyphicon glyphicon-log-in sign_in" href="/users/sign_in"> login</a></li>
      </li>
    <% end %>
  </ul>
</div>
</nav>
   <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>